# Composes SapoHub core + a set of util modules into a mix release.
#
# Each module is an attrset (the "module packaging attrset"):
#   {
#     name          = "my_plate";            # module id / dir name
#     app           = "my_plate";            # OTP app name
#     src           = ./modules/my_plate;    # source (path or store path)
#     elixirModule  = "MyPlate.Module";      # SapoKit.Module implementation
#     config        = { };                   # module config (registry)
#     cliFragment   = true;                  # has priv/cli/fragment.sh
#     jsHooks       = false;                 # has assets/hooks.js
#   }
#
# Codegen (postPatch, overwriting the checked-in dev defaults):
#   core/config/modules.lock.exs   - [{app, source_path}] for mix.exs deps
#   core/lib/sapo_core/generated/registry.ex - module list + config
#   core/assets/js/module_hooks.js - imports/merges module JS hooks
{ pkgs, lib, beamPkgs, elixir, tailwind }:

{ pname ? "sapohub"
, version ? "2.0.0"
, src                       # the SapoHub-2.0 repo
, modules                   # list of module packaging attrsets
, depsHash                  # FOD hash for fetchMixDeps over the composed tree
, npmDepsHash               # FOD hash for core/assets node_modules
}:

let
  # ── Codegen ────────────────────────────────────────────────────────────────

  # Modules are staged under modules/<name> inside the build tree. In-repo
  # modules already live there; external modules get copied in (identical
  # path-dep mechanism either way).
  lockEntries = lib.concatMapStringsSep ",\n  "
    (m: ''{:${m.app}, "../../modules/${m.name}"}'') modules;

  modulesLock = pkgs.writeText "modules.lock.exs" ''
    # GENERATED by nix (compose.nix) — do not edit.
    [
      ${lockEntries}
    ]
  '';

  registryModules = lib.concatMapStringsSep ", " (m: m.elixirModule) modules;

  registryConfig = lib.concatMapStringsSep ",\n      "
    (m: "${m.app}: ${toElixir (m.config or { })}") modules;

  # Minimal nix->elixir literal conversion for module config values.
  toElixir = v:
    if builtins.isAttrs v then
      "%{" + lib.concatStringsSep ", "
        (lib.mapAttrsToList (k: val: "${k}: ${toElixir val}") v) + "}"
    else if builtins.isList v then
      "[" + lib.concatMapStringsSep ", " toElixir v + "]"
    else if builtins.isBool v then (if v then "true" else "false")
    else if builtins.isInt v then toString v
    else ''"${toString v}"'';

  registry = pkgs.writeText "registry.ex" ''
    defmodule SapoCore.Generated.Registry do
      @moduledoc "GENERATED by nix (compose.nix) — do not edit."

      def modules do
        [${registryModules}]
      end

      def module_config do
        %{
          ${registryConfig}
        }
      end

      def config_for(mod) when is_atom(mod) do
        Map.get(module_config(), mod.id(), %{})
      end
    end
  '';

  hookModules = builtins.filter (m: m.jsHooks or false) modules;

  moduleHooksJs = pkgs.writeText "module_hooks.js" ''
    // GENERATED by nix (compose.nix) — do not edit.
    ${lib.concatMapStringsSep "\n"
      (m: ''import ${m.app}Hooks from "../../modules_js/${m.name}/hooks.js";'')
      hookModules}
    export default Object.assign({}, ${lib.concatMapStringsSep ", "
      (m: "${m.app}Hooks") hookModules});
  '';

  # Stage external module sources + codegen into the tree.
  composedSrc = pkgs.runCommand "${pname}-src" { } ''
    cp -r ${src} $out
    chmod -R u+w $out

    ${lib.concatMapStringsSep "\n" (m: ''
      rm -rf $out/modules/${m.name}
      mkdir -p $out/modules
      cp -r ${m.src} $out/modules/${m.name}
    '') modules}

    cp ${modulesLock} $out/core/config/modules.lock.exs
    cp ${registry}    $out/core/lib/sapo_core/generated/registry.ex

    mkdir -p $out/core/assets/modules_js
    ${lib.concatMapStringsSep "\n" (m: ''
      mkdir -p $out/core/assets/modules_js/${m.name}
      cp ${m.src}/assets/hooks.js $out/core/assets/modules_js/${m.name}/hooks.js
    '') hookModules}
    cp ${moduleHooksJs} $out/core/assets/js/module_hooks.js
  '';

  # ── Deps ───────────────────────────────────────────────────────────────────

  mixFodDeps = beamPkgs.fetchMixDeps {
    pname = "${pname}-deps";
    inherit version;
    src = composedSrc;
    sourceRoot = "${pname}-src/core";
    hash = depsHash;
  };

  # expty ships a precompiled NIF; pre-fetch it so elixir_make finds it in
  # its cache (network is blocked in the build sandbox).
  exptyNif = pkgs.fetchurl {
    url = "https://github.com/cocoa-xu/expty/releases/download/v0.2.1/expty-nif-2.16-x86_64-linux-gnu-0.2.1.tar.gz";
    hash = "sha256-HDLUODEpP6p0X/u0/HBux33V1pJb54xRF610F62HIcg=";
  };

  nodeModules = pkgs.stdenvNoCC.mkDerivation {
    name = "${pname}-node-modules";
    src = "${composedSrc}/core/assets";
    nativeBuildInputs = [ pkgs.nodejs pkgs.cacert ];
    buildPhase = ''
      export HOME=$TMPDIR
      npm ci --prefer-offline
    '';
    installPhase = ''cp -r node_modules $out'';
    outputHashAlgo = "sha256";
    outputHashMode = "recursive";
    outputHash = npmDepsHash;
    SSL_CERT_FILE = "${pkgs.cacert}/etc/ssl/certs/ca-bundle.crt";
  };

in beamPkgs.mixRelease {
  inherit pname version elixir mixFodDeps;
  src = composedSrc;
  sourceRoot = "${pname}-src/core";

  nativeBuildInputs = [
    pkgs.nodejs
    pkgs.esbuild
    pkgs.patchelf
    pkgs.stdenv.cc.cc.lib
  ];

  # Nix-built tailwind v4 / esbuild instead of downloaded binaries
  # (see config/config.exs: TAILWIND_PATH; esbuild uses the mix default
  # download unless MIX_ESBUILD_PATH — we set both defensively).
  TAILWIND_PATH = "${tailwind}/bin/tailwindcss";
  ESBUILD_PATH = "${pkgs.esbuild}/bin/esbuild";
  ELIXIR_MAKE_CACHE_DIR = "/tmp/elixir_make_cache";

  preConfigure = ''
    mkdir -p $ELIXIR_MAKE_CACHE_DIR
    cp ${exptyNif} $ELIXIR_MAKE_CACHE_DIR/expty-nif-2.16-x86_64-linux-gnu-0.2.1.tar.gz
  '';

  preBuild = ''
    cp -r ${nodeModules} assets/node_modules
    chmod -R u+w assets/node_modules
  '';

  postBuild = ''
    mkdir -p priv/static/assets
    # deps.loadpaths runs FIRST with --no-deps-check so the git-dep lock
    # check (heroicons has a gutted .git from fetchMixDeps) is skipped for
    # every subsequent task in this invocation.
    mix do deps.loadpaths --no-deps-check + assets.deploy
  '';

  postInstall = ''
    # Patch the expty spawn-helper for the NixOS dynamic linker.
    for f in $(find $out -name "spawn-helper" -type f); do
      patchelf \
        --set-interpreter "$(cat ${pkgs.stdenv.cc}/nix-support/dynamic-linker)" \
        --set-rpath "${pkgs.stdenv.cc.cc.lib}/lib" \
        "$f" || true
    done
  '';
}
