# sapohub-deploy — the ONE root-executed command (restricted sudoers).
#
# The config-repo path and flake attr are BAKED IN from the nix options, so
# no user-controlled paths ever reach root. The rebuild runs detached in a
# transient systemd unit (survives sapohub.service restarting itself), and
# the deploy streams the journal.
{ pkgs, lib }:

{ flakePath   # e.g. "/home/sapo/hub-config" (a git checkout)
, flakeAttr   # e.g. "nixos"
, stateDir    # e.g. "/var/lib/sapohub"
}:

pkgs.writeShellScriptBin "sapohub-deploy" ''
  set -euo pipefail
  export PATH="${lib.makeBinPath [
    pkgs.git pkgs.coreutils pkgs.systemd pkgs.nixos-rebuild pkgs.gzip pkgs.jq
  ]}:$PATH"

  FLAKE_PATH="${flakePath}"
  FLAKE_ATTR="${flakeAttr}"
  STATE_DIR="${stateDir}"

  SNAPSHOT=""
  while [ $# -gt 0 ]; do
    case "$1" in
      --snapshot)
        SNAPSHOT="$2"; shift 2 ;;
      *)
        echo "usage: sapohub-deploy [--snapshot <file>]" >&2; exit 1 ;;
    esac
  done

  # Stage a snapshot for boot-time restore (root-owned copy; the app's
  # Release.maybe_restore consumes it in ExecStartPre).
  if [ -n "$SNAPSHOT" ]; then
    [ -f "$SNAPSHOT" ] || { echo "snapshot not found: $SNAPSHOT" >&2; exit 1; }
    mkdir -p "$STATE_DIR/db/restore"
    cp "$SNAPSHOT" "$STATE_DIR/db/restore/pending.tar.gz"
    chmod 600 "$STATE_DIR/db/restore/pending.tar.gz"
    echo "snapshot staged for restore on next boot"
  fi

  git config --global --add safe.directory "$FLAKE_PATH" || true

  echo "pulling $FLAKE_PATH ..."
  git -C "$FLAKE_PATH" pull --ff-only

  # Sync the UI preference overlay into the config repo as a REAL nix
  # module file (lib.mkDefault, so hand-written config always wins). The
  # user's flake imports ./sapohub-prefs.nix. After a successful sync the
  # overlay is consumed — the nix config now carries the prefs.
  OVERLAY="$STATE_DIR/db/prefs-overlay.json"
  if [ -f "$OVERLAY" ] && [ -s "$OVERLAY" ]; then
    echo "syncing UI preferences into $FLAKE_PATH/sapohub-prefs.nix ..."

    BASE="{}"
    [ -f /etc/sapohub/prefs.json ] && BASE=$(cat /etc/sapohub/prefs.json)
    MERGED=$(jq -S -n --argjson base "$BASE" --argjson overlay "$(cat "$OVERLAY")" \
      '$base + $overlay')

    cat > "$FLAKE_PATH/sapohub-prefs.nix" <<NIXEOF
  # GENERATED by sapohub-deploy — UI preferences synced from the hub.
  # lib.mkDefault: anything you set on services.sapohub.prefs directly wins.
  { lib, ... }:
  {
    services.sapohub.prefs = lib.mapAttrs (_: lib.mkDefault) (builtins.fromJSON '''
  $MERGED
  ''');
  }
  NIXEOF

    git -C "$FLAKE_PATH" add sapohub-prefs.nix
    if ! git -C "$FLAKE_PATH" diff --cached --quiet; then
      git -C "$FLAKE_PATH" commit -m "sapohub: sync UI preferences"
      git -C "$FLAKE_PATH" push
    fi
    rm -f "$OVERLAY"
  fi

  echo "starting rebuild (detached; streaming journal — Ctrl-C safe) ..."
  systemd-run --unit=sapohub-deploy --collect --no-block \
    nixos-rebuild switch --flake "$FLAKE_PATH#$FLAKE_ATTR"

  exec journalctl -u sapohub-deploy -f --no-pager
''
