# sapohub-deploy — the ONE root-executed command (restricted sudoers).
#
# The config-repo path and flake attr are BAKED IN from the nix options, so
# no user-controlled paths ever reach root. The rebuild runs detached in a
# transient systemd unit (survives sapohub.service restarting itself), and
# the deploy streams the journal.
#
# Nix/git is the source of truth by default: a bare `sapohub-deploy` run
# (by hand over SSH, cron, whatever) pulls the config repo and rebuilds
# from EXACTLY what's there — it never lets a local runtime overlay of UI
# preferences override hand-written config. Only `--sync-prefs` opts in to
# writing that overlay back into the repo first; the Settings "Deploy"
# button is the one caller that passes it (see core/config/runtime.exs).
{ pkgs, lib }:

{ flakePath   # e.g. "/home/sapo/hub-config" (a git checkout)
, flakeAttr   # e.g. "nixos"
, stateDir    # e.g. "/var/lib/sapohub"
, secretsFile # e.g. "/etc/sapohub/secrets.env" — root-only; may hold GITHUB_TOKEN
}:

pkgs.writeShellScriptBin "sapohub-deploy" ''
  set -euo pipefail
  export PATH="${lib.makeBinPath [
    pkgs.git pkgs.coreutils pkgs.gnused pkgs.gnugrep pkgs.systemd pkgs.nixos-rebuild pkgs.gzip pkgs.jq
  ]}:$PATH"

  FLAKE_PATH="${flakePath}"
  FLAKE_ATTR="${flakeAttr}"
  STATE_DIR="${stateDir}"
  SECRETS_FILE="${secretsFile}"

  # GITHUB_TOKEN (if present in the root-only secrets file) authenticates
  # the config-repo push below. This script already runs as root, so
  # reading a root-owned 0600 file here doesn't widen access to anything.
  # Optional: no token just means the --sync-prefs commit below succeeds
  # locally but can't push (same as today, before this existed).
  GITHUB_TOKEN=""
  if [ -r "$SECRETS_FILE" ]; then
    GITHUB_TOKEN="$(grep -m1 '^GITHUB_TOKEN=' "$SECRETS_FILE" | cut -d= -f2- || true)"
  fi

  SNAPSHOT=""
  SYNC_PREFS=""
  while [ $# -gt 0 ]; do
    case "$1" in
      --snapshot)
        SNAPSHOT="$2"; shift 2 ;;
      --sync-prefs)
        SYNC_PREFS="1"; shift ;;
      *)
        echo "usage: sapohub-deploy [--snapshot <file>] [--sync-prefs]" >&2; exit 1 ;;
    esac
  done

  # Stage a snapshot for boot-time restore (root-owned copy; the app's
  # Release.maybe_restore consumes it in ExecStartPre).
  if [ -n "$SNAPSHOT" ]; then
    [ -f "$SNAPSHOT" ] || { echo "snapshot not found: $SNAPSHOT" >&2; exit 1; }
    mkdir -p "$STATE_DIR/db/restore"
    cp "$SNAPSHOT" "$STATE_DIR/db/restore/pending.tar.gz"
    chmod 600 "$STATE_DIR/db/restore/pending.tar.gz"
    echo "snapshot staged for restore on next boot"
  fi

  git config --global --add safe.directory "$FLAKE_PATH" || true

  echo "pulling $FLAKE_PATH ..."
  git -C "$FLAKE_PATH" pull --ff-only

  # Sync the UI preference overlay into the config repo as a REAL nix
  # module file (lib.mkDefault, so hand-written config always wins). The
  # user's flake imports ./sapohub-prefs.nix. After a successful sync the
  # overlay is consumed — the nix config now carries the prefs.
  #
  # ONLY when --sync-prefs is passed. Without it (the default — any bare
  # manual run) this whole step is skipped: the overlay file is left
  # exactly as-is (nothing lost, still live at runtime, still there for a
  # future --sync-prefs run) and the rebuild below uses whatever's
  # already committed in the config repo, unmodified. That's what makes
  # git/nix authoritative for manual deploys.
  OVERLAY="$STATE_DIR/db/prefs-overlay.json"
  if [ "$SYNC_PREFS" = "1" ] && [ -f "$OVERLAY" ] && [ -s "$OVERLAY" ]; then
    echo "syncing UI preferences into $FLAKE_PATH/sapohub-prefs.nix ..."

    BASE="{}"
    [ -f /etc/sapohub/prefs.json ] && BASE=$(cat /etc/sapohub/prefs.json)
    MERGED=$(jq -S -n --argjson base "$BASE" --argjson overlay "$(cat "$OVERLAY")" \
      '$base + $overlay')

    cat > "$FLAKE_PATH/sapohub-prefs.nix" <<NIXEOF
  # GENERATED by sapohub-deploy — UI preferences synced from the hub.
  # lib.mkDefault: anything you set on services.sapohub.prefs directly wins.
  { lib, ... }:
  {
    services.sapohub.prefs = lib.mapAttrs (_: lib.mkDefault) (builtins.fromJSON '''
  $MERGED
  ''');
  }
  NIXEOF

    git -C "$FLAKE_PATH" add sapohub-prefs.nix
    if ! git -C "$FLAKE_PATH" diff --cached --quiet; then
      # This runs as root via sudo, whose git identity is never
      # otherwise configured on a fresh machine — `git commit` would
      # abort with "Please tell me who you are" before ever reaching
      # the rebuild. Pass an explicit identity so this automated
      # commit never depends on host git config existing.
      git -c user.name="sapohub-deploy" -c user.email="sapohub-deploy@localhost" \
        -C "$FLAKE_PATH" commit -m "sapohub: sync UI preferences"

      if [ -n "$GITHUB_TOKEN" ]; then
        # Push over an authenticated URL built just for this one push —
        # never written to $FLAKE_PATH/.git/config, never in an argv any
        # non-root process could read (this whole script only runs as
        # root already).
        REMOTE_URL="$(git -C "$FLAKE_PATH" remote get-url origin)"
        AUTH_URL="$(printf '%s' "$REMOTE_URL" | sed "s|https://|https://x-access-token:$GITHUB_TOKEN@|")"
        git -C "$FLAKE_PATH" push "$AUTH_URL"
      else
        # Deliberately NOT attempting a bare `git push` here — without a
        # token it's certain to fail ("could not read Username"), and
        # under `set -e` that would abort the whole script before ever
        # reaching the rebuild below. The commit stays local; it'll push
        # next time --sync-prefs runs with a token present.
        echo "GITHUB_TOKEN not set in $SECRETS_FILE — commit made locally but not pushed" >&2
      fi
    fi
    rm -f "$OVERLAY"
  elif [ -f "$OVERLAY" ] && [ -s "$OVERLAY" ]; then
    echo "skipping UI preference sync (no --sync-prefs) — git/nix config takes precedence"
  fi

  echo "starting rebuild (detached; streaming journal — Ctrl-C safe) ..."
  # systemd-run does NOT inherit this script's PATH — transient units start
  # with systemd's own minimal default env, not the invoking shell's. That
  # silently broke nixos-rebuild-ng, which shells out to the `test`
  # coreutils binary internally and can't find it without coreutils on
  # PATH: it failed deep into the build with "[Errno 2] No such file or
  # directory: 'test'", after minutes of otherwise-successful work.
  # --setenv carries the PATH set at the top of this script through.
  systemd-run --unit=sapohub-deploy --collect --no-block \
    --setenv=PATH="$PATH" \
    nixos-rebuild switch --flake "$FLAKE_PATH#$FLAKE_ATTR"

  exec journalctl -u sapohub-deploy -f --no-pager
''
