defmodule Mix.Tasks.Sapo.Gen.Hooks do
  @shortdoc "Assemble module_hooks.js from enabled modules' assets/hooks.js"

  @moduledoc """
  Regenerates `assets/js/module_hooks.js`, importing and merging every
  enabled module's `assets/hooks.js` (per the modules lock file) into a
  single default export of LiveView hooks — the dev equivalent of what
  `nix/compose.nix` does for releases.

      mix sapo.gen.hooks

  Unlike the release build (which stages a copy of every module under
  `modules_js/` so import paths are uniform inside the composed tree),
  this task imports each module's `assets/hooks.js` directly from
  `../../modules/<name>/` — dev modules already live there as siblings of
  `core/`, so no staging copy is needed.

  Run automatically by `mix assets.build` / `assets.deploy`. Re-run by
  hand after adding `assets/hooks.js` to a module or editing
  `config/modules.lock.exs` — the esbuild watcher (`mix phx.server`)
  picks up further edits to an already-imported `hooks.js` on its own,
  since esbuild's watch mode follows the resolved import graph.
  """

  use Mix.Task

  @impl true
  def run(_args) do
    lock =
      System.get_env(
        "SAPOHUB_MODULES_LOCK",
        Path.join(File.cwd!(), "config/modules.lock.exs")
      )

    {modules, _binding} = Code.eval_file(lock)
    dest_dir = Path.join(File.cwd!(), "assets/js")

    hook_modules =
      for {app, path} <- modules,
          hooks_path = Path.expand(Path.join(path, "assets/hooks.js"), Path.dirname(lock)),
          File.exists?(hooks_path) do
        %{app: app, import_path: Path.relative_to(hooks_path, dest_dir, force: true)}
      end

    imports =
      Enum.map_join(hook_modules, "\n", fn %{app: app, import_path: path} ->
        ~s(import #{hook_var(app)} from "#{path}";)
      end)

    exports = Enum.map_join(hook_modules, ", ", fn %{app: app} -> hook_var(app) end)

    content = """
    // GENERATED by `mix sapo.gen.hooks` — do not edit directly.
    // Dev equivalent of nix/compose.nix's module_hooks.js generation.
    #{imports}

    export default Object.assign({}, #{exports});
    """

    dest = Path.join(dest_dir, "module_hooks.js")
    File.write!(dest, content)

    Mix.shell().info(
      "module_hooks.js written to #{dest} " <>
        "(#{length(hook_modules)} module(s) with hooks: #{Enum.map_join(hook_modules, ", ", & &1.app)})"
    )
  end

  defp hook_var(app), do: "#{Macro.camelize(to_string(app))}Hooks"
end
