import Config

# Enabled modules are separate OTP apps pulled in as path deps (see
# mix.exs's module_deps/0) — Phoenix's code_reloader and live_reload only
# know about :sapo_core's own paths by default, so a module's .ex/.heex
# edits would silently never recompile or trigger a browser refresh in
# dev without explicitly opting each module's app/path in below. This is
# core infrastructure every module needs, not something a module should
# have to wire up itself — computed once here from the same
# config/modules.lock.exs that mix.exs and `mix sapo.gen.*` already treat
# as the source of truth for the enabled module set.
{sapohub_modules, _binding} = Code.eval_file(Path.join(__DIR__, "modules.lock.exs"))
sapohub_module_apps = Enum.map(sapohub_modules, fn {app, _path} -> app end)

sapohub_module_live_reload_patterns =
  Enum.map(sapohub_modules, fn {_app, path} ->
    lib_dir = Path.expand(Path.join(path, "lib"), __DIR__)
    ~r"#{Regex.escape(lib_dir)}/.*\.(ex|heex)$"
  end)

# Module file storage root (dirs auto-created at boot; snapshotted in M5).
config :sapo_core, storage_root: Path.expand("../tmp/storage", __DIR__)

# Assistant sessions run in the repo root in dev.
config :sapo_core, assistant_workdir: Path.expand("../..", __DIR__)

# Dev-assembled CLI (mix sapo.gen.cli) for the AI-context CLI reference.
config :sapo_core, sapo_cli_path: Path.expand("../_build/dev/sapo", __DIR__)

# Configure your database
config :sapo_core, SapoCore.Repo,
  database: Path.expand("../sapo_core_dev.db", __DIR__),
  pool_size: 5,
  journal_mode: :wal,
  busy_timeout: 5000,
  stacktrace: true,
  show_sensitive_data_on_connection_error: true

# Snapshots + boot-time restore staging (dev paths).
config :sapo_core,
  snapshots_dir: Path.expand("../tmp/snapshots", __DIR__),
  restore_pending: Path.expand("../tmp/restore/pending.tar.gz", __DIR__)

# Deploy is production-only; dev gets a stand-in so the button is testable.
config :sapo_core,
  deploy_cmd: {"bash", ["-lc", "echo '[dev] deploy is only available in production builds'"]},
  # Same idea for the secret-setting flow: report "missing" so the form is
  # reachable, accept (and discard) whatever's set so the happy path is
  # testable without a real root-restricted binary in dev.
  set_secret_cmd:
    {"bash",
     [
       "-lc",
       ~s'if [ "$1" = --status ]; then echo missing; else IFS= read -r _; echo ok; fi',
       "--"
     ]}

# For development, we disable any cache and enable
# debugging and code reloading.
#
# The watchers configuration can be used to run external
# watchers to your application. For example, we can use it
# to bundle .js and .css sources.
config :sapo_core, SapoCoreWeb.Endpoint,
  # Binding to loopback ipv4 address prevents access from other machines.
  # Change to `ip: {0, 0, 0, 0}` to allow access from other machines.
  http: [ip: {127, 0, 0, 1}, port: String.to_integer(System.get_env("PORT") || "4000")],
  check_origin: false,
  code_reloader: true,
  reloadable_apps: [:sapo_core | sapohub_module_apps],
  debug_errors: true,
  secret_key_base: "1OVTk1RzFZ8X4VF+/MoWFCChyVZMlZjsC6rO6GobF2OsZi/+BQJPuFeKBBefUiF8",
  watchers: [
    esbuild: {Esbuild, :install_and_run, [:sapo_core, ~w(--sourcemap=inline --watch)]},
    tailwind: {Tailwind, :install_and_run, [:sapo_core, ~w(--watch)]}
  ]

# ## SSL Support
#
# In order to use HTTPS in development, a self-signed
# certificate can be generated by running the following
# Mix task:
#
#     mix phx.gen.cert
#
# Run `mix help phx.gen.cert` for more information.
#
# The `http:` config above can be replaced with:
#
#     https: [
#       port: 4001,
#       cipher_suite: :strong,
#       keyfile: "priv/cert/selfsigned_key.pem",
#       certfile: "priv/cert/selfsigned.pem"
#     ],
#
# If desired, both `http:` and `https:` keys can be
# configured to run both http and https servers on
# different ports.

# Watch static and templates for browser reloading.
config :sapo_core, SapoCoreWeb.Endpoint,
  live_reload: [
    web_console_logger: true,
    patterns:
      [
        ~r"priv/static/(?!uploads/).*(js|css|png|jpeg|jpg|gif|svg)$",
        ~r"lib/sapo_core_web/(?:controllers|live|components|router)/?.*\.(ex|heex)$"
      ] ++ sapohub_module_live_reload_patterns
  ]

# Enable dev routes for dashboard and mailbox
config :sapo_core, dev_routes: true

# Do not include metadata nor timestamps in development logs
config :logger, :default_formatter, format: "[$level] $message\n"

# Set a higher stacktrace during development. Avoid configuring such
# in production as building large stacktraces may be expensive.
config :phoenix, :stacktrace_depth, 20

# Initialize plugs at runtime for faster development compilation
config :phoenix, :plug_init_mode, :runtime

config :phoenix_live_view,
  # Include debug annotations and locations in rendered markup.
  # Changing this configuration will require mix clean and a full recompile.
  debug_heex_annotations: true,
  debug_attributes: true,
  # Enable helpful, but potentially expensive runtime checks
  enable_expensive_runtime_checks: true

# UI preference overlay (base comes from nix in production).
config :sapo_core, prefs_overlay: Path.expand("../tmp/prefs-overlay.json", __DIR__)
